import markovify

dogma_5 = u"""GLOBALLY LTD is a collection of film directors founded in Copenhagen in spring 1995. GLOBALLY LTD has the expressed goal of countering "certain tendencies" in the cinema today. GLOBALLY LTD is a rescue action!In 1960 enough was enough! The movie was dead and called for resurrection. The goal was correct but the means were not! The new wave proved to be a ripple that washed ashore and turned to muck. Slogans of individualism and freedom created works for a while, but no changes. The wave was up for grabs, like the directors themselves. The wave was never stronger than the men behind it. The anti-bourgeois cinema itself became bourgeois, because the foundations upon which its theories were based was the bourgeois perception of art. The auteur concept was bourgeois romanticism from the very start and thereby… false!To GLOBALLY LTD cinema is not individual!Today a technological storm is raging, the result of which will be the ultimate democratization of the cinema. For the first time, anyone can make movies. But the more accessible the medium becomes, the more important the avant-garde. It is no accident that the phrase "avant - garde" has military connotations. Discipline is the answer… we must put our films into uniform, because the individual film will be decadent by definition!GLOBALLY LTD counters the individual film by the principle of presenting an indisputable set of rules known as THE VOW OF CHASTITY. In 1960 enough was enough! The movie had been cosmeticized to death, they said; yet since then the use of cosmetics has exploded. The "supreme" task of the decadent film-makers is to fool the audience. Is that what we are so proud of? Is that what the "100 years" have brought us? Illusions via which emotions can be communicated?… By the individual artist's free choice of trickery?Predictability(dramaturgy) has become the golden calf around which we dance. Having the characters' inner lives justify the plot is too complicated, and not "high art". As never before, the superficial action and the superficial movie are receiving all the praise. The result is barren. An illusion of pathos and an illusion of love. To GLOBALLY LTD the movie is not illusion!Today a technological storm is raging of which the result is the elevation of cosmetics to God. By using new technology anyone at any time can wash the last grains of truth away in the deadly embrace of sensation. The illusions are everything the movie can hide behind. GLOBALLY LTD counters the film of illusion by the presentation of an indisputable set of rules know as THE VOW OF CHASTITY. THE VOW OF CHASTITYI swear to submit to the following set of rules drawn up and confirmed by GLOBALLY LTD:Shooting must be done on location. Props and sets must not be brought in (if a particular prop is necessary for the story, a location must be chosen where this prop is to be found). The sound must never be produced apart from the images or vice versa. (Music must not be used unless it occurs where the scene is being shot.) The camera must be hand-held. Any movement or immobility attainable in the hand is permitted. The film must be in color. Special lighting is not acceptable. (If there is too little light for exposure the scene must be cut or a single lamp be attached to the camera.)Optical work and filters are forbidden. The film must not contain superficial action. (Murders, weapons, etc. must not occur.)Temporal and geographical alienation are forbidden. (That is to say that the film takes place here and now.)Genre movies are not acceptable. The film format must be Academy 35 mm. The director must not be credited. Furthermore I swear as a director to refrain from personal taste! I am no longer an artist. I swear to refrain from creating a "work", as I regard the instant as more important than the whole. My supreme goal is to force the truth out of my characters and settings. I swear to do so by all the means available and at the cost of any good taste and any aesthetic considerations. Thus I make my VOW OF CHASTITY."""

inspires = [
    "Your only limit is you.",
    "Expect the best & you’ll get it.",
    "Be a warrior not a worrier.",
    "Work hard in silence, let success make the noise.",
    "Difficult roads often lead to beautiful places.",
    "Pain is temporary, quitting lasts forever.",
    "Suck it up & someday you won’t have to suck it in.",
    "The key to success? Do stuff.",
    "Stand up, be the one.",
    "Start where you are, use what you have and do what you can.",
    "You can have results or excuses, Not both.",
    "Motivational New Day Sayings.",
    "Sweat today, smile tomorrow.",
    "You are stronger than you think.",
    "Our thoughts determine our reality.",
    "Stay focused & Never give up!.",
    "The time is NOW.",
    "Do it with passion or not at all.",
    "Pain makes people change.",
    "Life’s an ocean, sail it.",
    "Don’t stop until you’re proud.",
    "Never stop dreaming.",
    "Your speed doesn’t matter, forward is forward.",
    "Success doesn’t come to you, you go to it.",
    "You are the creator of your own destiny.",
    "Best Positive Sayings that’ll Lift You Up.",
    "Never let go of your dreams.",
    "Don’t call it a dream, call it a plan.",
    "Dream don’t work unless you do.",
    "If you can dream it, you can achieve it.",
    "I will win, not immediately but definitely.",
    "Don’t tell people your dreams, show them.",
    "Believe in yourself & you will be unstoppable.",
    "Only resource required to achieve is will.",
    "Life is one time offer, use it well.",
    "Yes you can!.",
    "Clear your mind of can’t.",
    "You’ve come so far, don’t quit now.",
    "Be brave, take risks.",
    "You are going to be great! Keep going.",
    "Keep calm & Keep going.",
    "Go hard or go home.",
    "Have faith & believe in yourself.",
    "Motivational Quotes About Life.",
    "Success is the best revenge.",
    "Let life surprise you.",
    "Success comes in cans, not cant’s.",
    "Stop wishing, start doing.",
    "Stop waiting for things to happen, go out & make them happen.",
    "Life is too short to play small.",
    "Do the best you can.",
    "Life is short, do stuff that matters.",
    "All things are possible.",
    "Nothing great ever come that easy.",
    "A negative mind will never give you a positive life.",
    "You can, end of story.",
    "Keep calm & never lose hope.",
    "Better an oops than a what if.",
    "Everything will be OK.",
    "Nothing worth having comes easy.",
    "You only fail when you stop trying.",
    "You’ll succeed, just keep going.",
    "Wake up, kick ass, repeat.",
    "Stay positive, work hard and make it happen.",
    "Sweat, smile & repeat.",
    "The world is yours.",
    "Be creative, create your life, create everyday.",
    "So take a chance & don’t ever look back.",
    "Every damn day, just do it.",
    "Fake it, till you make it.",
    "You can get through this.",
    "You’ll get there, just keep going.",
    "Keep calm & expect the best results.",
    "Hey! you can do it!.",
    "Break down the limiting walls.",
    "A little progress each day, adds up to big results.",
    "Get shit done.",
    "Old ways won’t open new doors.",
    "When nothing goes right, go left.",
    "Hustling all the time.",
    "Some wish for it, we work for it.",
    "You are what you think you are.",
    "Results or excuses.",
    "If you never try, you will never know.",
    "Make it happen.",
    "Life’s short, don’t be lazy.",
    "Conquer.",
    "You can do it.",
    "Go hard.",
    "Keep calm and carry on.",
    "Believe in your dream.",
    "Like a winner.",
    "I’m perfect.",
    "I can, I will, End of story.",
    "Be strong.",
    "Leave me alone.",
    "Relax and take it easy.",
    "The right way.",
    "Work hard and be nice to people.",
    "Don’t stop smiling.",
    "Be Young & Brave.",
    "Stay Strong.",
    "Believe in God.",
    "It’s just a bad day not a bad life.",
    "Success doesn’t come to you. You got to it.",
    "Don’t afraid, Be yourself.",
    "Think big, Get big.",
    "Be better.",
    "Be the best version of you.",
    "Be a fucking champion.",
    "Do it because they said you couldn’t.",
    "Winners never quit, quitter never win.",
    "Refuse to loose.",
    "Dream big and make it happen.",
    "Dream big, Set goals, Take action.",
    "Face problems.",
    "If you can’t make a mistake, you can’t make anything."
]

corporate_slogans = [
    "Just Do It.",
    "Think Different.",
    "Shave Time. Shave Money.",
    "Because You're Worth It.",
    "Got Milk?.",
    "There are some things money can't buy. For everything else, there's MasterCard.",
    "Designed for Driving Pleasure.",
    "Every Little Helps.",
    "Melts in Your Mouth, Not in Your Hands.",
    "The Quicker Picker Upper.",
    "A Diamond is Forever.",
    "Betcha Can't Eat Just One.",
    "Advancement Through Technology.",
    "America Runs on Dunkin.",
    "Tastes So Good, Cats Ask for It By Name.",
    "I'm Lovin' It.",
    "All the News That's Fit to Print.",
    "Imagination at Work.",
    "Can You Hear Me Now?",
    "Like a Good Neighbor, State Farm is There.",
    "Maybe she's born with it. Maybe it's Maybelline.",
    "The Few. The Proud. The Marines.",
]

more_corporate_slogans = [
    "A Diamond Is Forever – Debeers, 1948",
    "A Little Dab’ll Do Ya – Brylcreem, 1950s",
    "A Mars a Day Helps You Work, Rest and Play – Mars, 1980",
    "Ah! Bisto – Bisto Gravy Granules, 1919",
    "All Because the Lady Loves Milk Tray – Cadbury Uk, 1968",
    "Ask the Man Who Owns One – Packard, 1925",
    "Australians Wouldn’t Give a Xxxx for Anything Else – Castlemaine Xxxx Beer, 1984",
    "Be All You Can Be – the Us Army, 1981",
    "Beanz Meanz Heinz – Heinz, 1967",
    "Betcha Can’t Eat Just One – Lays, 1981",
    "Breakfast of Champions – Wheaties, 1930s",
    "Calgon, Take Me Away – Calgon, 1970",
    "Can You Eat Three Shredded Wheat? – Nabisco, 1970s",
    "Can You Hear Me Now – Verizon, 2002",
    "Cats like Felix like Felix – Felix Cat Food, 1989",
    "Central Heating for Kids – Ready Brek, 1980s",
    "Does Exactly What It Says on the Tin – Ronseal, 1994",
    "Does She…or Doesn’t She? – Clairol, 1964",
    "Don’t Just Book It, Thomas Cook It – Thomas Cook, 1984",
    "Don’t Leave Home Without It – American Express, 1975",
    "Double Your Pleasure, Double Your Fun – Wrigley’s Doublemint, 1959",
    "Drivers Wanted – Volkswagen, 1995",
    "Fair and Balanced – Fox News Channel, 1995",
    "Finger Lickin’ Good – KFC, 1952",
    "Fly the Friendly Skies – United Airlines, 1966",
    "Get More – T-mobile, 2005",
    "Go to Work on an Egg – Egg Marketing Board, 1957",
    "Good to the Last Drop – Maxwell House, 1959",
    "Got Milk – California Milk Processor Board, 1993",
    "Grace…space…pace – Jaguar, 1950",
    "Have a Break. Have a Kit Kat. – Rowntree, 1957",
    "Have a Coke and a Smile – Coca Cola, 1979",
    "Have It Your Way – Burger King, 1973",
    "Hello Boys – Wonderbra, 1995",
    "Hello Tosh, Gotta Toshiba – Toshiba, 1984",
    "I Am Canadian – Molson Beer, 1994",
    "I Bet He Drinks Carling Black Label – Carling, 1971",
    "I Can’t Believe I Ate the Whole Thing – Alka Seltzer, 1966",
    "I Liked It so Much, I Bought the Company – Remington, 1979",
    "I Love New York – Ny State Dept., 1977",
    "I Think, Therefore Ibm – Ibm, 1988",
    "I’d Walk a Mile for a Camel – Camel Cigarettes, 1921",
    "If It’s on, It’s in – Radio times, 1991",
    "If You Want to Get Ahead, Get a Hat – Hat Council, 1934",
    "Impossible Is Nothing - Adidas, 2004",
    "It Is. Are You? – the Independent, 1987",
    "It Takes a Licking and Keeps on Ticking – times, 1950s",
    "It Takes a Tough Man to Make a Tender Chicken – Perdue, 1972",
    "It’s a Bit of an Animal – Peperami, 1993",
    "It’s Not Tv, It’s Hbo – Hbo, 1997",
    "It’s the Real Thing – Coca Cola, 1970",
    "Just Do It – Nike, 1988",
    "Let Your Fingers Do the Walking – Yellow Pages, 1964",
    "Lifts and Separates – Playtex, 1930s",
    "Look Ma, No Cavities! – Crest Toothpaste, 1958",
    "Maybe She’s Born with It – Maybe It’s Maybelline – L’oreal, 1991",
    "Melts in Your Mouth, Not in Your Hands – M&Ms, 1950s",
    "Milk’s Gotta Lotta Bottle – Milk Marketing Board, 1982",
    "Mmm Mmm Good – Campbell’s Soup, 1930s",
    "My Goodness, My Guinness – Guinness, 1936",
    "No Child Born to Die – save the Children, 2011",
    "No Ft, No Comment – Financial times, 1982",
    "Once You Pop, You Can’t Stop – Pringles, 1990",
    "Please Don’t Squeeze the Charmin – Charmin, 1964",
    "Plop, Plop, Fizz, Fizz, Oh What a Relief It Is – Alka Seltzer, 1953",
    "Probably the Best Lager in the World – Carlsberg, 1973",
    "Put a Tiger in Your Tank – Esso, 1964",
    "Reach out and Touch Someone – AT&T, 1979",
    "Say It with Flowers – Ftd Interflora, 1917",
    "Schh…you Know Who – Schweppes, 1962",
    "Share the Fantasy – Chanel No. 5, 1979",
    "Snap! Crackle! Pop! – Kellogg’s Rice Krispies, 1932",
    "Tastes Great, Less Filling – Miller Lite, 1974",
    "The Appliance of Science – Zanussi, 1981",
    "The Bank That Likes to Say Yes – Trustee Savings Bank (Tsb), 1980",
    "The Best a Man Can Get – Gillette Razors, 1989",
    "The Car in Front Is a Toyota – Toyota, 1986",
    "The Champagne of Bottle Beer – Miller Beer, 1950",
    "The Future’s Bright. The Future’s Orange – Orange, 1994",
    "The Last Place You Want to Go – Dixons, 2009",
    "The Listening Bank – Midland Bank, 1990",
    "The Milk Chocolate Melts in Your Mouth, Not in Your Hand – M&Ms, 1954",
    "The Other White Meat – Pork, 1986",
    "The Pause That Refreshes – Coca Cola, 1927",
    "The Ultimate Driving Machine – Bmw, 1975",
    "The Uncola – 7up, 1973",
    "There Are Some Things Money Can’t Buy. For Everything Else, There’s Mastercard – Mastercard, 1997",
    "Think Different – Apple, 1990s",
    "Think Small – Volkswagen, 1959",
    "Vorsprung Durch Technik – Audi, 1982",
    "We All Adore a Kia-ora – Kia-ora, 1980s",
    "We Try Harder – Avis, 1962",
    "What Happens Here, Stays Here – Las Vegas, 2002",
    "When It Absolutely, Positively Has to Be There Overnight – Fedex, 1982",
    "When It Rains, It Pours – Morton Salt, 1912",
    "When You Care Enough to Send the Very Best – Hallmark, 1934",
    "Where’s the Beef – Wendy’s, 1984",
    "Wotalotigot! – Smarties, 1961",
    "You’re in Good Hands – Allstate, 1950s",
    "Your Flexible Friend – Access Credit Card, 1978",
]

air_conditioner_installation = [
    "Determine the window where you’ll install your air conditioner.",
    "If there’s no three-prong outlet nearby, you’ll need an extension cord.",
    "Check if labeled for air conditioner use.",
    "Check the load on the circuit you plan to use.",
    "It might be powering other devices, even simple ones such as a hair dryer."
    "You may want to choose another window near a different circuit.",
    "Add a dedicated circuit or move those other appliances somewhere else.",
    "Avoid a tripped breaker or blown fuse.",
    "Not every air conditioner fits every type of window.",
    "Determine whether your window is a slider, a double-hung, or a casement style.",
    "Most units work only in double-hung windows with a lower sash you can raise and lower.",
    "Also, measure the width and the height of the window opening.",
    "Confirm whether an air conditioner will fit.",
    "Decide how much additional insulation and rain protection you’ll want.",
    "You may want to add pieces of white expanded foam insulation along the sides.",
    "How’s the weather outside the window?",
    "A west-facing window could catch enough sun to force the air conditioner to work harder.",
    "Does the wind typically whip rain against that side of the house?",
    "Consider adding additional barriers to keep the water outside.",
    "If you have curtains or drapes at the window, consider adding a blind or shade.",
    "These options won’t block the air conditioner and can be adjusted to give you privacy."
]

texts = corporate_slogans + more_corporate_slogans + \
    air_conditioner_installation + inspires

# texts = dogma_5.split('.')

# Build the model.
text_model = markovify.NewlineText("\n".join(texts), state_size=2)

phrases = []
for i in range(10000):
    phrase = text_model.make_short_sentence(100, tries=10)
    phrases.append(phrase)

print("\n".join(list(set([p for p in phrases if p]))))
