/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/main.glb', draco('/draco-gltf/'))

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      insideout1: mixer.clipAction(animations[0], group.current),
      insideout2: mixer.clipAction(animations[1], group.current),
      insideout3: mixer.clipAction(animations[2], group.current),
      insideout4: mixer.clipAction(animations[3], group.current),
      mate1: mixer.clipAction(animations[4], group.current),
      mate2: mixer.clipAction(animations[5], group.current),
      roses1: mixer.clipAction(animations[6], group.current),
      roses2: mixer.clipAction(animations[7], group.current),
      roses3: mixer.clipAction(animations[8], group.current),
      roses4: mixer.clipAction(animations[9], group.current),
    }
    return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.mixamorigHips} />
      <skinnedMesh
        material={nodes.Body_Bodymesh.material}
        geometry={nodes.Body_Bodymesh.geometry}
        skeleton={nodes.Body_Bodymesh.skeleton}
      />
      <skinnedMesh
        material={nodes.Cylinder.material}
        geometry={nodes.Cylinder.geometry}
        skeleton={nodes.Cylinder.skeleton}
      />
      <skinnedMesh
        material={nodes.default_defaultmesh.material}
        geometry={nodes.default_defaultmesh.geometry}
        skeleton={nodes.default_defaultmesh.skeleton}
      />
      <skinnedMesh
        material={nodes.Eyelashes_Eyelashesmesh.material}
        geometry={nodes.Eyelashes_Eyelashesmesh.geometry}
        skeleton={nodes.Eyelashes_Eyelashesmesh.skeleton}
      />
    </group>
  )
}
