/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/main.glb', draco('/draco-gltf/'))

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    actions.current = {
      insideout1: mixer.clipAction(animations[0], group.current),
      insideout2: mixer.clipAction(animations[1], group.current),
      insideout3: mixer.clipAction(animations[2], group.current),
      insideout4: mixer.clipAction(animations[3], group.current),
      mate1: mixer.clipAction(animations[4], group.current),
      mate2: mixer.clipAction(animations[5], group.current),
      mate3: mixer.clipAction(animations[6], group.current),
      roses1: mixer.clipAction(animations[7], group.current),
    }
    return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.mixamorigHips} />
      <skinnedMesh
        material={nodes.Body_Bodymesh.material}
        geometry={nodes.Body_Bodymesh.geometry}
        skeleton={nodes.Body_Bodymesh.skeleton}
      />
      <skinnedMesh
        material={nodes.default_defaultmesh.material}
        geometry={nodes.default_defaultmesh.geometry}
        skeleton={nodes.default_defaultmesh.skeleton}
      />
      <skinnedMesh
        material={nodes.Eyelashes_Eyelashesmesh.material}
        geometry={nodes.Eyelashes_Eyelashesmesh.geometry}
        skeleton={nodes.Eyelashes_Eyelashesmesh.skeleton}
      />
      <skinnedMesh
      material={nodes.Hair07.material} geometry={nodes.Hair07.geometry} skeleton={nodes.Hair07.skeleton} />
      <skinnedMesh
      material={nodes.Torus.material}
      geometry={nodes.Torus.geometry}
      skeleton={nodes.Torus.skeleton} />
      <skinnedMesh
        material={nodes.Torus001.material}
        geometry={nodes.Torus001.geometry}
        skeleton={nodes.Torus001.skeleton}
      />
      <skinnedMesh
        material={nodes.Torus002_Torus004.material}
        geometry={nodes.Torus002_Torus004.geometry}
        skeleton={nodes.Torus002_Torus004.skeleton}
      />
      <skinnedMesh
        material={nodes.Torus003.material}
        geometry={nodes.Torus003.geometry}
        skeleton={nodes.Torus003.skeleton}
      />
      <skinnedMesh
        material={nodes.Torus004_Torus006.material}
        geometry={nodes.Torus004_Torus006.geometry}
        skeleton={nodes.Torus004_Torus006.skeleton}
      />
      <skinnedMesh
        material={nodes.Torus005.material}
        geometry={nodes.Torus005.geometry}
        skeleton={nodes.Torus005.skeleton}
      />
      <skinnedMesh
        material={nodes.Torus006_Torus008.material}
        geometry={nodes.Torus006_Torus008.geometry}
        skeleton={nodes.Torus006_Torus008.skeleton}
      />
      <skinnedMesh
        material={nodes.Torus007.material}
        geometry={nodes.Torus007.geometry}
        skeleton={nodes.Torus007.skeleton}
      />
    </group>
  )
}
